[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# The output dir for all final assets.
dist = "dist"
# The public URL from which assets are to be served.
public_url = "./"
# Whether to include hash values in the output file names.
filehash = true
